const feedMockups = {
  success: true,
  data: {
    not_seen_notifications: 11,
    cells: [
      {
        type: 'challenge',
        id: 396,
      },
      {
        type: 'article',
        id: 34021,
      },
      {
        type: 'article',
        id: 34020,
      },
      {
        type: 'article',
        id: 34019,
      },
      {
        type: 'article',
        id: 34018,
      },
      {
        type: 'article',
        id: 34017,
      },
      {
        type: 'article',
        id: 34016,
      },
      {
        type: 'article',
        id: 34015,
      },
      {
        type: 'article',
        id: 34014,
      },
      {
        type: 'article',
        id: 34013,
      },
      {
        type: 'article',
        id: 34012,
      },
      {
        type: 'article',
        id: 34011,
      },
      {
        type: 'article',
        id: 34010,
      },
      {
        type: 'article',
        id: 34009,
      },
      {
        type: 'article',
        id: 34008,
      },
      {
        type: 'article',
        id: 34007,
      },
      {
        type: 'article',
        id: 34006,
      },
      {
        type: 'article',
        id: 34005,
      },
      {
        type: 'article',
        id: 34004,
      },
      {
        type: 'article',
        id: 33911,
      },
    ],
    challenge: {
      id: 396,
      created: '2021-01-29 16:44:15',
      challenge: 985,
      user_id: 3,
      accepted: false,
      completed: false,
      new_challenge: true,
      challenge_points: 15,
      status: {
        status_text: 'Your challenge is to Start new poll',
        time_left: '07:15 Hrs LEFT',
        minutes_to_complete: 20,
        percent_who_completed: 50,
      },
    },
    last_cell_date: '2021-01-29T14:29:03.717583',
    articles: [
      {
        id: 34021,
        created: '2021-01-29 16:28:49',
        published_at: '2021-01-29 12:15:03',
        group_domain: '1611937729434',
        title: '3 new Mac tips for better online security',
        description:
          "Here is how to set up FileVault: Make sure that you are logged in as an administrator Click the Apple menu and then System Preferences From there, click Security & Privacy Navigate until you find FileVault Click Turn On FileVault You might be asked to input your Mac password and will then be presented with several choices.\nDisable automatic login If there are multiple users on one Mac, you'll want to lock down each profile.\nClick the Apple menu Click System Preferences , then Users & Groups From there, click the lock icon and enter the account password In the lower-left corner, click Login Options Select the user whose account you wish to change The first option should be Automatic Login Turn it off If you followed the steps above to set up FileVault, Automatic Login would be unavailable as FileVault requires a manual login.\nA manual login will also be required if the selected user signs in with an iCloud password.\nHere is how you turn on the firewall: Click the Apple menu and then System Preferences Click Security or Security & Privacy Select the Firewall tab Unlock the pane by clicking the lock in the lower-left corner and enter the administrator username and password Click Turn On Firewall or Start to enable the firewall Once activated, you will be able to configure it to your liking.",
        your_rating: null,
        url: 'https://www.techregister.co.uk/3-new-mac-tips-for-better-online-security/',
        image: 'content_providers_logos/aylien_logo_default.png',
        manager: {
          network_id: 1028,
          full_name: 'Shared by the system',
          image: 'content_providers_logos/trust-net_logo.png',
          current_role: '',
        },
        background_color: [206.0, 186.0, 204.0],
        is_video: false,
        source_image: 'content_providers_logos/aylien_logo_circle.png',
        unread_count: 0,
        cover_photo: 'content_providers_logos/aylien_logo_default.png',
        rating_count: 0,
        like_count: 0,
        view_count: 0,
        comments_count: 0,
        pinned: false,
        members_count: 23,
      },
      {
        id: 34020,
        created: '2021-01-29 16:28:49',
        published_at: '2021-01-29 12:15:06',
        group_domain: '1611937729054',
        title: 'Regional Cooperation Key to Mideast Peace, Zarif Tells Arab Neighbours',
        description:
          '“Dear neighbours, ahead of us lies an opportunity to once again think about regional security,” he said.\n“We know that security cannot be bought, nor can it be established by stockpiling weapons,” he noted.\nHe said Iran has always announced its readiness to help trigger regional cooperation to establish peace and security in the region.',
        your_rating: null,
        url: 'https://world.einnews.com/article/535127946/bOocL6ECrc8jZoxf',
        image:
          'generated_articles/Regional Cooperation Key to Mideast Peace, Zarif Tells Arab Neighbours.jpg',
        manager: {
          network_id: 1028,
          full_name: 'Shared by the system',
          image: 'content_providers_logos/trust-net_logo.png',
          current_role: '',
        },
        background_color: [123.0, 174.0, 167.0],
        is_video: false,
        source_image: 'content_providers_logos/aylien_logo_circle.png',
        unread_count: 0,
        cover_photo:
          'generated_articles/Regional Cooperation Key to Mideast Peace, Zarif Tells Arab Neighbours.jpg',
        rating_count: 0,
        like_count: 0,
        view_count: 0,
        comments_count: 0,
        pinned: false,
        members_count: 23,
      },
      {
        id: 34019,
        created: '2021-01-29 16:28:48',
        published_at: '2021-01-29 12:15:26',
        group_domain: '1611937728604',
        title: 'Kibo Code Quantum: THe 5 Step eCommerce Store Building Process By Steve Clayton',
        description:
          'Aidan Booth and Steve Clayton released a new program that reveals a 5-step system for creating a 6-figure eCommerce business selling physical products without any inventory or overseas suppliers.If you want to learn how you can implement this altervative approach to selling physical products, join our webinar at https :// go.\ncom / webreg2On January 24, in a members-only workshop, Steve Clayton revealed that the changes they had made to the Kibo Code system would enable users to set up, grow and scale their businesses at a faster pace.\nKibo Code Quantum will also come with additional new expert training sessions, bonuses, and many other platform updates.Users will be able to build a life-changing business on the back of Facebook Marketplace and using other free traffic sources.\nThey get access to training and resources targeted precisely for the needs of entrepreneurs who want to build a sustainable and profitable business.The eCommerce mentors, Steve Clayton and Aidan Booth have tried to run away from the expensive additional apps and help users save on the monthly Shopify fees, initially required for running effectively and profitably the Kibo Code System.\nCurrent users have expressed their hopes that Kibo Code Quantum will feature a new Kibo store interface and solve any platform bugs and error messages.Regardless of the level of their expertise, users are guaranteed a tested method for building a profitable dropshipping business without the need for Amazon, risky inventory purchases, overseas suppliers or Shopify.By joining the program, users can take advantage of the Quantum eCom effect and learn how to use free traffic to generate targeted traffic, conversions and sales of third party goods.The cost of the program is $3997, which can be divided into 4 installments of $997 each.You can also learn about the Kibo Code Quantum features and bonuses at https :// muncheye.',
        your_rating: null,
        url:
          'http://prsync.com/pr-agency/kibo-code-quantum-the--step-ecommerce-store-building-process-by-steve-clayton-3366363/',
        image: 'content_providers_logos/aylien_logo_default.png',
        manager: {
          network_id: 1028,
          full_name: 'Shared by the system',
          image: 'content_providers_logos/trust-net_logo.png',
          current_role: '',
        },
        background_color: [150.0, 189.0, 252.0],
        is_video: false,
        source_image: 'content_providers_logos/aylien_logo_circle.png',
        unread_count: 0,
        cover_photo: 'content_providers_logos/aylien_logo_default.png',
        rating_count: 0,
        like_count: 0,
        view_count: 0,
        comments_count: 0,
        pinned: false,
        members_count: 23,
      },
      {
        id: 34018,
        created: '2021-01-29 16:28:48',
        published_at: '2021-01-29 12:18:37',
        group_domain: '1611937728263',
        title: 'Ubuntu vs Mint: Which one is better?',
        description:
          "Screenshot of the Linux Mint operating system user interface Linux Mint is comparably younger than Ubuntu - not surprising as it's based upon the platform.\nWhile Ubuntu has software company Canonical behind it to run its development, Linux Mint relies on individual users and companies using the OS to act as sponsors, donors and partners.\nProductivity When installed, both Ubuntu and Linux Mint feature Libre Office productivity suite and Firefox browser.\nThis is where Ubuntu scores one against Linux Mint; it is easier to find apps within its store than with Mint.\nUbuntu also features paid apps, whereas Linux Mint doesn't.",
        your_rating: null,
        url: 'https://www.itpro.com/operating-systems/25139/ubuntu-vs-mint-which-one-is-better',
        image: 'generated_articles/Ubuntu vs Mint  Which one is better .jpg',
        manager: {
          network_id: 1028,
          full_name: 'Shared by the system',
          image: 'content_providers_logos/trust-net_logo.png',
          current_role: '',
        },
        background_color: [194.0, 190.0, 59.0],
        is_video: false,
        source_image: 'content_providers_logos/aylien_logo_circle.png',
        unread_count: 0,
        cover_photo: 'generated_articles/Ubuntu vs Mint  Which one is better .jpg',
        rating_count: 0,
        like_count: 0,
        view_count: 0,
        comments_count: 0,
        pinned: false,
        members_count: 23,
      },
      {
        id: 34017,
        created: '2021-01-29 16:28:48',
        published_at: '2021-01-29 12:21:06',
        group_domain: '1611937727942',
        title:
          'Emotet taken down in major international operation, but is the malware gone for good?',
        description:
          'The post Emotet taken down in major international operation, but is the malware gone for good?\nappeared first on Computer Business Review.A major operation by security agencies from around the world saw critical infrastructure behind the Emotet botnet taken offline this week, but the malware which has helped earn criminal gangs millions of dollars could return, security experts say.Emotet, which is used as a door opener to infect systems and allow threat actors to deploy secondary malwares or ransomware attacks, has been a prominent cyber threat since 2014.\nOn Wednesday Europol announced that 700 of its servers had been taken offline....',
        your_rating: null,
        url:
          'https://www.techinvestornews.com/Enterprise/Latest-Enterprise-News/emotet-taken-down-in-major-international-operation-but-is-the-malware-gone-',
        image: 'content_providers_logos/aylien_logo_default.png',
        manager: {
          network_id: 1028,
          full_name: 'Shared by the system',
          image: 'content_providers_logos/trust-net_logo.png',
          current_role: '',
        },
        background_color: [59.0, 23.0, 167.0],
        is_video: false,
        source_image: 'content_providers_logos/aylien_logo_circle.png',
        unread_count: 0,
        cover_photo: 'content_providers_logos/aylien_logo_default.png',
        rating_count: 0,
        like_count: 0,
        view_count: 0,
        comments_count: 0,
        pinned: false,
        members_count: 23,
      },
      {
        id: 34016,
        created: '2021-01-29 16:28:47',
        published_at: '2021-01-29 12:23:22',
        group_domain: '1611937727582',
        title: 'Opening Esri Personal Geodatabase (*.mdb) using QGIS?',
        description:
          'Add the following two lines:set OGR_SKIP=ODBC set PGEO_DRIVER_TEMPLATE=DRIVER=Microsoft Access Driver (*.\naccdb);DBQ=%%sStep 3Open QGIS and drag the mdb file onto your workspaceVoila!Provided you have successfully installed Microsoft Access Database Engine 64 bit, you can:Method 1 (works with QGIS 2) add the following two lines:set OGR_SKIP=ODBC set PGEO_DRIVER_TEMPLATE=DRIVER=Microsoft Access Driver (*.\nbat before the last line, that usually is something like start "QGIS" /B "%OSGEO4W_ROOT%"\\bin\\qqis...[note that there are two percent signs in the value of PGEO_DRIVER_TEMPLATE variable]Method 2 (works with QGIS 3)In QGIS Settings panel -> Options | System | Environment add the following two variables:variable name: OGR_SKIP value: ODBC variable name: PGEO_DRIVER_TEMPLATE value: DRIVER=Microsoft Access Driver (*.\naccdb);DBQ=%s and check the "Use custom variables" checkbox[note that in this case there is only one percent sign in the value of PGEO_DRIVER_TEMPLATE variable]Method 3 (works with both QGIS 2 and QGIS 3)In the Environment Variables panel of the Windows Advanced System Settings, set the following two new variables as User Variables or System Variables:variable name: OGR_SKIP value: ODBC variable name: PGEO_DRIVER_TEMPLATE value: DRIVER=Microsoft Access Driver (*.\naccdb);DBQ=%s[note that also in this case there is only one percent sign in the value of PGEO_DRIVER_TEMPLATE variable]The solution proposed works fine also on windows 10.',
        your_rating: null,
        url:
          'https://gis.stackexchange.com/questions/129514/opening-esri-personal-geodatabase-mdb-using-qgis',
        image: 'generated_articles/Opening Esri Personal Geodatabase *.mdb using QGIS .png',
        manager: {
          network_id: 1028,
          full_name: 'Shared by the system',
          image: 'content_providers_logos/trust-net_logo.png',
          current_role: '',
        },
        background_color: [66.0, 195.0, 171.0],
        is_video: false,
        source_image: 'content_providers_logos/aylien_logo_circle.png',
        unread_count: 0,
        cover_photo: 'generated_articles/Opening Esri Personal Geodatabase *.mdb using QGIS .png',
        rating_count: 0,
        like_count: 0,
        view_count: 0,
        comments_count: 0,
        pinned: false,
        members_count: 23,
      },
      {
        id: 34015,
        created: '2021-01-29 16:28:47',
        published_at: '2021-01-29 12:25:12',
        group_domain: '1611937727206',
        title: "Frost's National Security Adviser Appointment Scrapped",
        description:
          'Plans for Lord Frost to become the UK’s new national security advisor have been scrapped over fears his departure from his current EU-facing role would lead to too great a loss of institutional knowledge.\nWhen Mark Sedwell was dismissed last June, it was announced his role would be split in two, with Frost getting the security brief and a new figure to replace him as Cabinet Secretary.',
        your_rating: null,
        url:
          'https://order-order.com/2021/01/29/david-frosts-national-security-adviser-appointment-scrapped/?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+guidofawkes+%28Guy+Fawkes%27+blog+of+parliamentary+plots%2C+rumours+and+conspiracy%29',
        image:
          "generated_articles/Frost's National Security Adviser Appointment Scrapped.jpg?fit=1908%2C1146&ssl=1",
        manager: {
          network_id: 1028,
          full_name: 'Shared by the system',
          image: 'content_providers_logos/trust-net_logo.png',
          current_role: '',
        },
        background_color: [53.0, 63.0, 192.0],
        is_video: false,
        source_image: 'content_providers_logos/aylien_logo_circle.png',
        unread_count: 0,
        cover_photo:
          "generated_articles/Frost's National Security Adviser Appointment Scrapped.jpg?fit=1908%2C1146&ssl=1",
        rating_count: 0,
        like_count: 0,
        view_count: 0,
        comments_count: 0,
        pinned: false,
        members_count: 23,
      },
      {
        id: 34014,
        created: '2021-01-29 16:28:46',
        published_at: '2021-01-29 12:27:20',
        group_domain: '1611937726792',
        title: 'Windows Package Manager getting an uninstall option very soon',
        description:
          "That Windows Package Manager exists at all is a big step forward, but while the service is in preview it is rather limited.\nAt present you can use it to find and install software but removing it has to be done the old fashioned way.\nAnd who wants to do that?It may sound like a small update but it's a huge deal for users of Windows Package Manager and will make it something users can start to really rely on.\nThe update has been submitted to the Microsoft Store for existing users and will be pushing out pretty soon.Windows Package Manager is very similar to the package managers you'd use on Linux in the terminal, and on Windows will eventually be a first-party alternative to something likeChocolatey.\nIt's not necessarily for everyone, which is fine, but there are plenty of use cases where a tool like this will make software deployment, and soon removal, much more efficient.Microsoft enters the next console generation strong with Xbox Series X and Xbox Series S, pushing steady growth across its hardware, software, and subscriptions in Q2 financials.To prepare for Rare's maiden voyage into seasonal content updates, we sat down with Executive Producer Joe Neate and Creative Director Mike Chapman to discuss all the big things coming with Season One and what the future of this pirate sandbox game holds.Dell's lineup includes both convertible and non-convertible versions of the XPS 13, and while they're both premium options, there are some similarities and differences to note before deciding on which will be your next PC.",
        your_rating: null,
        url: 'https://www.windowscentral.com/windows-package-manager-getting-uninstall-option',
        image:
          'generated_articles/Windows Package Manager getting an uninstall option very soon.png',
        manager: {
          network_id: 1028,
          full_name: 'Shared by the system',
          image: 'content_providers_logos/trust-net_logo.png',
          current_role: '',
        },
        background_color: [124.0, 87.0, 116.0],
        is_video: false,
        source_image: 'content_providers_logos/aylien_logo_circle.png',
        unread_count: 0,
        cover_photo:
          'generated_articles/Windows Package Manager getting an uninstall option very soon.png',
        rating_count: 0,
        like_count: 0,
        view_count: 0,
        comments_count: 0,
        pinned: false,
        members_count: 23,
      },
      {
        id: 34013,
        created: '2021-01-29 16:28:46',
        published_at: '2021-01-29 12:13:04',
        group_domain: '1611937726456',
        title:
          'Teams and Zoom: “School principals became data protection fundamentalists” – Digital',
        description:
          'Data protection law does set conditions, but these can be fulfilled both with open-source conference software such as Big Blue Button and with Microsoft Teams.\nSchool principals confuse the whimsy of privacy advocates who would prefer to shut Google, Microsoft and the USA off the Internet with the much lower requirements of the GDPR.\nSchools and teachers avoid US providers such as Zoom or Microsoft because they believe that the GDPR prohibits their use.\nAt the schools in Würzburg I know, students and parents have given the necessary consent.\nIn a guest post at Network policy A high school student from Hessen does not demand less, but more data protection.',
        your_rating: null,
        url:
          'https://www.newsylist.com/teams-and-zoom-school-principals-became-data-protection-fundamentalists-digital/',
        image: 'content_providers_logos/aylien_logo_default.png',
        manager: {
          network_id: 1028,
          full_name: 'Shared by the system',
          image: 'content_providers_logos/trust-net_logo.png',
          current_role: '',
        },
        background_color: [87.0, 63.0, 208.0],
        is_video: false,
        source_image: 'content_providers_logos/aylien_logo_circle.png',
        unread_count: 0,
        cover_photo: 'content_providers_logos/aylien_logo_default.png',
        rating_count: 0,
        like_count: 0,
        view_count: 0,
        comments_count: 0,
        pinned: false,
        members_count: 23,
      },
      {
        id: 34012,
        created: '2021-01-29 16:28:46',
        published_at: '2021-01-29 12:16:20',
        group_domain: '1611937726134',
        title: 'UK resumes privacy oversight of adtech, warns platform audits are coming',
        description:
          "The high velocity trading of Internet users' personal data can't possibly be compliant with GDPR's requirement that such information is adequately secured, the complaints contend.\nOther concerns attached to real-time bidding (RTB) focus on consent, questioning how this can meet the required legal standard with data being broadcast to so many companies — including sensitive information, such as health data or religious and political affiliation and sexual orientation.",
        your_rating: null,
        url:
          'http://vectornews.eu/news/technologies/268989-uk-resumes-privacy-oversight-of-adtech-warns-platform-audits-are-coming.html',
        image: 'content_providers_logos/aylien_logo_default.png',
        manager: {
          network_id: 1028,
          full_name: 'Shared by the system',
          image: 'content_providers_logos/trust-net_logo.png',
          current_role: '',
        },
        background_color: [49.0, 150.0, 90.0],
        is_video: false,
        source_image: 'content_providers_logos/aylien_logo_circle.png',
        unread_count: 0,
        cover_photo: 'content_providers_logos/aylien_logo_default.png',
        rating_count: 0,
        like_count: 0,
        view_count: 0,
        comments_count: 0,
        pinned: false,
        members_count: 23,
      },
      {
        id: 34011,
        created: '2021-01-29 16:28:45',
        published_at: '2021-01-29 12:17:36',
        group_domain: '1611937725774',
        title: '50% Indian IT leaders see permanent rise in value of data: Druva report',
        description:
          'Or, read more from the original publisher:\n\nHalf of Indian IT leaders see a permanent increase in the value of data as organisations accelerate digital transformation, according to a report by Druva, a cloud data protection and management firm.\nThe ‘Value of Data’ report, based on responses from over 1,000 IT decision-makers in India, the United States and the United Kingdom, also found rising concerns among Indian businesses about data protection and the growing role data agility plays in enabling organisational operations and connecting with customers.\nFrom the over 300 respondents in India, a third reported an increase in ransomware attacks since the pandemic began, and overall 89% of respondents being more concerned now with protecting their organizational data from ransomware than before the pandemic.\nThe survey reveals that protecting data from outside threats, unauthorised internal access and ensuring business resiliency are becoming key priorities for organisations as they accelerate their cloud migration and digital transformation plans.\nThe survey found that the time to recover data remains an issue for 67% of the respondents and has increased since the pandemic, while a quarter said that their companies can only go three to four hours without access to data before causing serious harm to their business.',
        your_rating: null,
        url:
          'https://asiapedia.net/2021/01/29/50-indian-it-leaders-see-permanent-rise-in-value-of-data-druva-report/',
        image:
          'generated_articles/50% Indian IT leaders see permanent rise in value of data  Druva report.jpg?fit=1070%2C580&ssl=1',
        manager: {
          network_id: 1028,
          full_name: 'Shared by the system',
          image: 'content_providers_logos/trust-net_logo.png',
          current_role: '',
        },
        background_color: [13.0, 2.0, 146.0],
        is_video: false,
        source_image: 'content_providers_logos/aylien_logo_circle.png',
        unread_count: 0,
        cover_photo:
          'generated_articles/50% Indian IT leaders see permanent rise in value of data  Druva report.jpg?fit=1070%2C580&ssl=1',
        rating_count: 0,
        like_count: 0,
        view_count: 0,
        comments_count: 0,
        pinned: false,
        members_count: 23,
      },
      {
        id: 34010,
        created: '2021-01-29 16:28:45',
        published_at: '2021-01-29 12:18:28',
        group_domain: '1611937725398',
        title:
          'Suspected Russian Hack Extends Far Beyond SolarWinds Software, Investigators Say | MarketScreener',
        description:
          "Hackers linked to the attack have broken into these systems by exploiting known bugs in software products, by guessing online passwords and by capitalizing on a variety of issues in the way Microsoft Corp.'s cloud-based software is configured, investigators said.\nThe attack surfaced in December, when security experts discovered hackers inserted a backdoor into updates to SolarWinds' software, called Orion, which was used widely across the federal government and by a swath of Fortune 500 companies.\nMr. Wales said his agency isn't aware of cloud software other than Microsoft's targeted in the attack.\nWhen the SolarWinds hack was first uncovered, current and former national security officials quickly concluded it was one of the worst breaches on record -- an intelligence coup that went undetected for several months or longer that allowed suspected Russian spies access to internal emails and other files in several government agencies.\nInvestigators still believe the primary purpose of the hacking campaign, which the government has said is ongoing, is to glean information by spying on federal agencies and high-value corporate networks -- or compromise other technology companies whose access could lead to follow-on attacks.",
        your_rating: null,
        url:
          'https://www.marketscreener.com/quote/stock/SOLARWINDS-CORPORATION-46661543/news/Suspected-Russian-Hack-Extends-Far-Beyond-SolarWinds-Software-Investigators-Say-32309001/?utm_medium=RSS&utm_content=20210129',
        image:
          'generated_articles/Suspected Russian Hack Extends Far Beyond SolarWinds Software, Investigators Say | MarketScreener.png',
        manager: {
          network_id: 1028,
          full_name: 'Shared by the system',
          image: 'content_providers_logos/trust-net_logo.png',
          current_role: '',
        },
        background_color: [117.0, 108.0, 151.0],
        is_video: false,
        source_image: 'content_providers_logos/aylien_logo_circle.png',
        unread_count: 0,
        cover_photo:
          'generated_articles/Suspected Russian Hack Extends Far Beyond SolarWinds Software, Investigators Say | MarketScreener.png',
        rating_count: 0,
        like_count: 0,
        view_count: 0,
        comments_count: 0,
        pinned: false,
        members_count: 23,
      },
      {
        id: 34009,
        created: '2021-01-29 16:28:45',
        published_at: '2021-01-29 12:19:00',
        group_domain: '1611937725063',
        title: 'Hong Kong tightens leash on mobile phone use, registration',
        description:
          "The new measure comes on the heels of China's decision to impose the new national security law on the semi-autonomous city last year.\nBut that has become a source of irritation for Hong Kong's security forces, as massive pro-democracy protests erupted in the city between 2018 and 2019.\nUnder the new proposal, businesses are also required to provide company information to register, while individual users are allowed to have only three pay-to-go cards from one telecom provider.\nSonny Au, Hong Kong Authority's under-secretary of security, explained that the proposed real-name registration is meant to curb criminality, phone harassment, prostitution and even online extortion.\nChina has signalled a more hands-on approach to Hong Kong affairs early last year when it replaced the heads of the Liaison Office in the city.",
        your_rating: null,
        url:
          'https://indiatimespost.com/hong-kong-tightens-leash-on-mobile-phone-use-registration/',
        image: 'generated_articles/Hong Kong tightens leash on mobile phone use, registration.jpg',
        manager: {
          network_id: 1028,
          full_name: 'Shared by the system',
          image: 'content_providers_logos/trust-net_logo.png',
          current_role: '',
        },
        background_color: [233.0, 146.0, 27.0],
        is_video: false,
        source_image: 'content_providers_logos/telecom.png',
        unread_count: 0,
        cover_photo:
          'generated_articles/Hong Kong tightens leash on mobile phone use, registration.jpg',
        rating_count: 0,
        like_count: 0,
        view_count: 0,
        comments_count: 0,
        pinned: false,
        members_count: 23,
      },
      {
        id: 34008,
        created: '2021-01-29 16:28:44',
        published_at: '2021-01-29 12:19:44',
        group_domain: '1611937724749',
        title: 'Personal Data Stolen From Dutch Coronavirus Track-and-trace Programme',
        description:
          'AMSTERDAM: Personal information of a large number of people who participated in the Netherlands’ coronavirus track-and-trace programme has been leaked, the Dutch health authorities (GGD) said on Friday.\nThe GGD confirmed a media report that data had been stolen and apologised for what it said were two separate leaks.\nThe GGD said the data leaks were from its core track-and-trace system, and not related to a tracking smartphone app that had been closely scrutinised for potential privacy weaknesses.\n“If people who mean ill intentionally take data out of a system, that’s almost impossible to stop,” the GGD said.\nThe GGD confirmed the leaks included names, addresses, social security numbers, telephone numbers, and test results.',
        your_rating: null,
        url:
          'https://www.news18.com/news/world/personal-data-stolen-from-dutch-coronavirus-track-and-trace-programme-3361460.html',
        image:
          'generated_articles/Personal Data Stolen From Dutch Coronavirus Track-and-trace Programme.jpg',
        manager: {
          network_id: 1028,
          full_name: 'Shared by the system',
          image: 'content_providers_logos/trust-net_logo.png',
          current_role: '',
        },
        background_color: [7.0, 198.0, 17.0],
        is_video: false,
        source_image: 'content_providers_logos/aylien_logo_circle.png',
        unread_count: 0,
        cover_photo:
          'generated_articles/Personal Data Stolen From Dutch Coronavirus Track-and-trace Programme.jpg',
        rating_count: 0,
        like_count: 0,
        view_count: 0,
        comments_count: 0,
        pinned: false,
        members_count: 23,
      },
      {
        id: 34007,
        created: '2021-01-29 16:28:44',
        published_at: '2021-01-29 12:25:48',
        group_domain: '1611937724376',
        title: 'Stranded Australians’ Data “unintentionally” Shared',
        description:
          'The Australian government admitted to unintentionally sharing sensitive passenger information with one of the department’s consular clients.\nThis data breach occurred on January 24th, in which passenger’s full name, gender, date of birth, email address, passport details (number, expiry, issuing country), Australian citizenship status, phone number, current location, and flight booking reference of those booked on the flight had been accidentally copied into an email and sent.\nThe Australian Government Department of Foreign Affairs and Trade (Dfat) stated that it took “immediate action to mitigate any impact resulting from the inadvertent sharing of a flight manifest.”\nDfat claimed the email has been deleted by the receiving party, whoever the consular client remains unknown.\nThe Australian government, however, remains open to scheduling further repatriation flights.',
        your_rating: null,
        url:
          'https://www.itsecurityguru.org/2021/01/29/stranded-australians-data-unintentionally-shared/?utm_source=rss&utm_medium=rss&utm_campaign=stranded-australians-data-unintentionally-shared',
        image: 'generated_articles/Stranded Australians’ Data “unintentionally” Shared.jpg',
        manager: {
          network_id: 1028,
          full_name: 'Shared by the system',
          image: 'content_providers_logos/trust-net_logo.png',
          current_role: '',
        },
        background_color: [62.0, 163.0, 247.0],
        is_video: false,
        source_image: 'content_providers_logos/aylien_logo_circle.png',
        unread_count: 0,
        cover_photo: 'generated_articles/Stranded Australians’ Data “unintentionally” Shared.jpg',
        rating_count: 0,
        like_count: 0,
        view_count: 0,
        comments_count: 0,
        pinned: false,
        members_count: 23,
      },
      {
        id: 34006,
        created: '2021-01-29 16:28:44',
        published_at: '2021-01-29 12:26:05',
        group_domain: '1611937723947',
        title: "How Apple’s new privacy ‘nutrition labels' might be misleading you",
        description: '',
        your_rating: null,
        url:
          'https://www.washingtonpost.com/video/technology/upgrade-with-geoffrey-fowler/how-apples-new-privacy-nutrition-labels-might-be-misleading-you/2021/01/29/d1f3e5fe-b09b-43e2-8125-cc4d0a550018_video.html?utm_source=rss&utm_medium=referral&utm_campaign=wp_business',
        image:
          "generated_articles/How Apple’s new privacy ‘nutrition labels' might be misleading you.jpg&w=1484&op=resize&opt=1&filter=antialias&t=20170517",
        manager: {
          network_id: 1028,
          full_name: 'Shared by the system',
          image: 'content_providers_logos/trust-net_logo.png',
          current_role: '',
        },
        background_color: [240.0, 37.0, 241.0],
        is_video: false,
        source_image: 'content_providers_logos/aylien_logo_circle.png',
        unread_count: 0,
        cover_photo:
          "generated_articles/How Apple’s new privacy ‘nutrition labels' might be misleading you.jpg&w=1484&op=resize&opt=1&filter=antialias&t=20170517",
        rating_count: 0,
        like_count: 0,
        view_count: 0,
        comments_count: 0,
        pinned: false,
        members_count: 23,
      },
      {
        id: 34005,
        created: '2021-01-29 16:28:43',
        published_at: '2021-01-29 12:29:17',
        group_domain: '1611937723422',
        title:
          "'Somewhat unique senior staffing change': Hamden mayor appoints former Hamden mayor as finance director",
        description:
          'We use third-party services for commenting, videos, and embedding posts as part of our news coverage.\nThe providers of these cookies may use the data as explained in their privacy policies.Twitter(Facebook(Select AllPerformance, Content Recommendation and Personalization CookiesWe use our own and third-party services to provide content recommendations and customize your user experience and advertising.\nThe providers of these cookies may use the data as explained in their privacy policies.',
        your_rating: null,
        url:
          'https://www.mysanantonio.com/news/article/Somewhat-unique-senior-staffing-change-15906923.php',
        image:
          "generated_articles/'Somewhat unique senior staffing change'  Hamden mayor appoints former Hamden mayor as finance director.jpg",
        manager: {
          network_id: 1028,
          full_name: 'Shared by the system',
          image: 'content_providers_logos/trust-net_logo.png',
          current_role: '',
        },
        background_color: [39.0, 230.0, 145.0],
        is_video: false,
        source_image: 'content_providers_logos/aylien_logo_circle.png',
        unread_count: 0,
        cover_photo:
          "generated_articles/'Somewhat unique senior staffing change'  Hamden mayor appoints former Hamden mayor as finance director.jpg",
        rating_count: 0,
        like_count: 0,
        view_count: 0,
        comments_count: 0,
        pinned: false,
        members_count: 23,
      },
      {
        id: 34004,
        created: '2021-01-29 16:28:43',
        published_at: '2021-01-29 12:12:00',
        group_domain: '1611937722981',
        title: 'New CISOs Survey Reveals How Small Cybersecurity Teams Can Confront 2021',
        description:
          ' The pressure on small to medium-sized enterprises to protect their organizations against cyberthreats is astronomical. These businesses face the same threats as the largest enterprises, experience the same (relative) damages and consequences when breaches occur as the largest enterprises but are forced to protect their organizations with a fraction of the resources as the largest enterprises.   Cybersecurity company Cynet just released findings from a survey of 200 CISOs in charge of small security teams ( Download here ) to shine "a spotlight into the challenges of small security teams everywhere."  In addition to better understanding the challenges these CISOs face, the 2021 Survey of CISOs with Small Security Teams delves into the strategies CISOs will employ to ensure their organizations are protected from the ongoing onslaught of cyber threats - all while saddled with limited budgets and headcount.  The survey findings will also be presented in a live webinar,  register',
        your_rating: null,
        url: 'https://thehackernews.com/2021/01/new-cisos-survey-reveals-how-small.html',
        image:
          'generated_articles/New CISOs Survey Reveals How Small Cybersecurity Teams Can Confront 2021.jpg',
        manager: {
          network_id: 1028,
          full_name: 'Shared by the system',
          image: 'content_providers_logos/trust-net_logo.png',
          current_role: '',
        },
        background_color: [20.0, 233.0, 118.0],
        is_video: false,
        source_image: 'content_providers_logos/the_hacker_news.jpg',
        unread_count: 0,
        cover_photo:
          'generated_articles/New CISOs Survey Reveals How Small Cybersecurity Teams Can Confront 2021.jpg',
        rating_count: 0,
        like_count: 0,
        view_count: 0,
        comments_count: 0,
        pinned: false,
        members_count: 23,
      },
      {
        id: 33911,
        created: '2021-01-29 14:29:03',
        published_at: '2021-01-27 12:07:41',
        group_domain: '1611930543593',
        title:
          "Emotet: 'World's most dangerous malware' botnet disrupted by international police operation",
        description:
          'Europol and FBI among agencies which have taken control of the botnet infrastructure used by cyber criminals behind some of the most prolific malware and ransomware attacks.',
        your_rating: null,
        url:
          'https://www.zdnet.com/article/emotet-worlds-most-dangerous-malware-botnet-disrupted-by-international-police-operation/#ftag=RSSbaffb68',
        image:
          "generated_articles/Emotet  'World's most dangerous malware' botnet disrupted by international police operation.jpg",
        manager: {
          network_id: 1028,
          full_name: 'Shared by the system',
          image: 'content_providers_logos/trust-net_logo.png',
          current_role: '',
        },
        background_color: [235.0, 118.0, 139.0],
        is_video: false,
        source_image: 'content_providers_logos/aylien_logo_circle.png',
        unread_count: 0,
        cover_photo:
          "generated_articles/Emotet  'World's most dangerous malware' botnet disrupted by international police operation.jpg",
        rating_count: 0,
        like_count: 0,
        view_count: 1,
        comments_count: 0,
        pinned: false,
        members_count: 23,
      },
    ],
  },
};

export default feedMockups;
